spring.application.name=equipamento
spring.profiles.active=test

server.port=8087

# Habilitación técnica de OpenAPI y Swagger UI para Equipamento
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

