spring.application.name=inscripciones
spring.profiles.active=test
server.port=8084

# Habilitación técnica de OpenAPI y Swagger UI para Inscripciones
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
