spring.application.name=gym.socios
spring.profiles.active=test

# Configuración Global de Swagger (Disponible en todo momento)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html