spring.application.name=contratos
server.port=8091
spring.profiles.active=test

# Habilitación técnica de OpenAPI y Swagger UI para Contratos
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
