spring.application.name=mantenimiento
spring.profiles.active=test

server.port=8089

# Habilitación técnica de OpenAPI y Swagger UI para Mantenimiento
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
