spring.application.name=proveedores
spring.profiles.active=test
server.port=8090

# Habilitación técnica de OpenAPI y Swagger UI para Proveedores
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


