spring.application.name=proveedores
spring.datasource.url=jdbc:mysql://localhost:3306/db_gym
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8090

# Habilitación técnica de OpenAPI y Swagger UI para Proveedores
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


