spring.application.name=sucursales
spring.profiles.active=test
# Puerto del servidor (Diferente a los demás)
server.port=8088



# Habilitación técnica de OpenAPI y Swagger UI para Sucursales
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
