spring.application.name=planes
spring.profiles.active=test
server.port=8081

# Habilitación técnica de OpenAPI y Swagger UI para Planes
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html